buses:
  - id: 1
    name: "Bus 1"
    v_nom: 230
  - id: 2
    name: "Bus 2"
    v_nom: 230
  - id: 3
    name: "Bus 3"
    v_nom: 230
  - id: 4
    name: "Bus 4"
    v_nom: 230
  - id: 5
    name: "Bus 5"
    v_nom: 230
  - id: 6
    name: "Bus 6"
    v_nom: 230
  - id: 7
    name: "Bus 7"
    v_nom: 230
  - id: 8
    name: "Bus 8"
    v_nom: 230
  - id: 9
    name: "Bus 9"
    v_nom: 230
  - id: 10
    name: "Bus 10"
    v_nom: 230
  - id: 11
    name: "Bus 11"
    v_nom: 230
  - id: 12
    name: "Bus 12"
    v_nom: 230
  - id: 13
    name: "Bus 13"
    v_nom: 230
  - id: 14
    name: "Bus 14"
    v_nom: 230

lines:
  - id: 1
    from_bus: 1
    to_bus: 2
    x: 0.01938
    s_nom: 130
  - id: 2
    from_bus: 1
    to_bus: 5
    x: 0.05403
    s_nom: 130
  - id: 3
    from_bus: 2
    to_bus: 3
    x: 0.04699
    s_nom: 130
  - id: 4
    from_bus: 2
    to_bus: 4
    x: 0.05811
    s_nom: 130
  - id: 5
    from_bus: 2
    to_bus: 5
    x: 0.05695
    s_nom: 130
  - id: 6
    from_bus: 3
    to_bus: 4
    x: 0.06701
    s_nom: 130
  - id: 7
    from_bus: 4
    to_bus: 5
    x: 0.01335
    s_nom: 130
  - id: 8
    from_bus: 4
    to_bus: 7
    x: 0.01
    s_nom: 130
  - id: 9
    from_bus: 4
    to_bus: 9
    x: 0.01
    s_nom: 130
  - id: 10
    from_bus: 5
    to_bus: 6
    x: 0.01
    s_nom: 130
  - id: 11
    from_bus: 6
    to_bus: 11
    x: 0.01
    s_nom: 130
  - id: 12
    from_bus: 6
    to_bus: 12
    x: 0.01
    s_nom: 130
  - id: 13
    from_bus: 6
    to_bus: 13
    x: 0.01
    s_nom: 130
  - id: 14
    from_bus: 9
    to_bus: 14
    x: 0.01
    s_nom: 130

generators:
  - id: 1
    bus: 1
    p_nom: 100
    marginal_cost: 40
  - id: 2
    bus: 2
    p_nom: 100
    marginal_cost: 40
  - id: 3
    bus: 3
    p_nom: 100
    marginal_cost: 40 